spring:
    application:
        name: ${SPRING_APPLICATION_NAME:mifos_reporting}
    datasource:
        driverClassName: ${SPRING_DATASOURCE_DRIVERCLASSNAME:org.h2.Driver}
        password: ${SPRING_DATASOURCE_PASSWORD:}  # Default to empty password
        jdbc-url: ${SPRING_DATASOURCE_JDBC_URL:jdbc:h2:file:/data/reports_db} 
        username: ${SPRING_DATASOURCE_USERNAME:sa}
    h2:
        console:
            enabled: true
            path: /h2-console
            settings:
              web-allow-others: true
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
        show-sql: true

report:
    datasource:
        driver-class-name: ${MIFOS_DB_DRIVERCLASSNAME:org.mariadb.jdbc.Driver}
        jdbc-url: ${MIFOS_DB_JDBC_URL:jdbc:mariadb://localhost:3306/mifos}
        password: ${MIFOS_DB_PASSWORD:root}
        username: ${MIFOS_DB_USERNAME:root}
