spring.application.name=mifos_reporting

#spring.datasource.url=jdbc:h2:mem:testDB_CLOSE_DELAY=-1
spring.datasource.url=jdbc:h2:file:~/reports_db
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driverClassName=org.h2.Driver

# Enable H2 Console access
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Hibernate configuration
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
## Format SQL in the logs
spring.jpa.properties.hibernate.format_sql=true
## Automatically update the schema
spring.jpa.hibernate.ddl-auto=update
## Show SQL in the logs
spring.jpa.show-sql=true